config/routes.rb
Rails.application.routes.draw do
devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  get 'add' => 'pages#add'

  resources :users

  resources :spots, only: [:index, :show, :new, :create, :edit, :update] do
    # resources :doses, only: [:new, :create] // pour faire plaisir au rake
    resources :bookings, only: [:index,:new, :create, :show, :edit, :update]
    resources :spot_reviews, only: [:index, :new, :create, :edit, :update, :destroy]

  end
end

app/models/spot.rb
class Spot < ActiveRecord::Base
  # alias_attribute :user, :owner
  belongs_to  :user
  has_many :photos
  has_many :bookings
  has_many :spot_reviews
  accepts_nested_attributes_for :photos, reject_if: lambda {|attributes| attributes['picture'].blank?}, :allow_destroy => true

  validates :title, presence: true, length: { maximum: 36, too_long: "limit to 36 characters" }
  validates :description, presence: true
  validates :price, presence: true
  validates :area, presence: true
  validates :style, presence: true
  validates :address, presence: true
  validates :exposition, presence: true, length: { maximum: 2, too_long: "Choose N, S, E, O, EO, etc." }
  validate :has_photo

  paginates_per 20

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def rating
    spot_reviews.average(:rating) || 0
  end

  def has_photo
    if photos.size == 1
      errors.add(:base, 'must have one photo')
    else
    end
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController

  before_action :set_spot, only: [:show, :edit, :update]
  before_action :set_params, only: [:index, :new]
  before_filter :store_location
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @spots = Spot.all

    @spots_selected = Spot.where(visible: true)

    if !(@params["city"].nil? || @params["city"] == "")
      # @spots_selected = @spots_selected.where("city = ?", @params["city"].capitalize)
      @spots_selected = @spots_selected.near(@params["city"], 50)
    end

    @max_price = @spots_selected.maximum('price')
    @min_price = @spots_selected.minimum('price')
    @max_area = @spots_selected.maximum('area')
    @min_area = @spots_selected.minimum('area')

    @max_rating = 0
    @spots_selected.each do |spot|
      @max_rating = spot.rating > @max_rating ? spot.rating : @max_rating
    end

    if !(@params["price"].nil? || @params["price"] == "")
      @spots_selected = @spots_selected.where("price <= ?", @params["price"].to_i)
    end
    if !(@params["style"].nil? || @params["style"] == "")
      @spots_selected = @spots_selected.where("style = ?", @params["style"].capitalize)
    end
    if !(@params["area"].nil? || @params["area"] == "")
      @spots_selected = @spots_selected.where("area >= ?", @params["area"].to_i)
    end

    if !(@params["exceptional_view"].nil? || @params["exceptional_view"] == "") \
      && @params["exceptional_view"] == "on"
      @spots_selected = @spots_selected.where("exceptional_view = ?", true)
    end

    if !(@params["exposition"].nil? || @params["exposition"] == "") \
      && @params["exposition"] == "on"
      @spots_selected = @spots_selected.where("exposition = ?", true)
    end

    if @params["rating"].present?
      @spots_selected = @spots_selected.joins(:spot_reviews).group('spots.id').having('AVG(spot_reviews.rating) >= ?', @params["rating"])
    end

    @spots_total_number = @spots_selected.length
    @spots_selected = @spots_selected.page params[:page]

    @markers = Gmaps4rails.build_markers(@spots_selected) do |spot, marker|
      @my_spot = spot
      marker.lat spot.latitude
      marker.lng spot.longitude
      # marker.infowindow render_to_string(:partial => "/spots/infowindow")
      marker.infowindow render_to_string(:partial => 'spots/infowindow', :locals => { :object => @my_spot})

      # marker.picture({
      #   :url => ActionController::Base.helpers.asset_path('marker.png'),#{ }"http://placehold.it/30x30",
      #   :width   => 28,
      #   :height  => 35
      #  })
    end
  end

  def show
    @owner = User.find(@spot.user_id)
    @spot_review = SpotReview.new
  end

  def new
    @spot = Spot.new
    @spot.price = @params["area"].to_i * 4
    # 2.times { @spot.photos.build }
  end

  def create
    @params = spot_params
    @spot = Spot.new(spot_params)
    # raise
    @spot.photos.build
    # @spot.photos.each { |photo| photo.build }
    # @spot.build_photo

    if @spot.save
      redirect_to spot_path(@spot)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @spot.update(spot_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private
  def set_spot
    id = params[:spot_id] || params[:id]
    @spot = Spot.find(id)
  end
  def set_params
    @params = params
  end
  def spot_params
    params.require(:spot).permit(:title, :address, :description, :price, :user_id,
      :visible, :style, :area, :exposition, :exceptional_view,
      :modular_furniture, photos_attributes: [:id, :picture, :_destroy])
  end
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/spots/_form.html.erb
<div class="background-grey">
  <div class="container">
    <div class="row">
      <%= simple_nested_form_for @spot do  |f| %>
        <div class="col-sm-5 col-sm-offset-1">
          <div class="margin-form">
            <%= f.input :title %>
            <%= f.input :description %>
            <%= f.input :address, placeholder: "" %>
            <%= f.input :area, input_html: { value: @params.nil? ? @spot.area : @params["area"]  } %>
            <%= f.input :style, collection: %w( chic rustique industriel cosy ) %>
          </div>
        </div>
        <div class="col-sm-5 col-sm-offset-1">
          <div class="margin-form">

            <%= f.input :exposition %>
            <%= f.input :exceptional_view %>
            <%= f.input :modular_furniture %>
            <%= f.input :price, label: 'Price per day' %>
            <%= f.hidden_field :visible, value: 'true' %>
            <%= f.hidden_field :user_id, value: current_user.id %>

            <p>Pictures</p>
            <div id="pics">
              <%= f.fields_for :photos do |photos_form| %>
                <%= photos_form.file_field :picture, class: 'inline' %><%= photos_form.link_to_remove ('<i class="fa fa-trash"></i>').html_safe, class: 'inline' %>
              <% end %>
              <p><%= f.link_to_add ('<i class="fa fa-plus"></i>').html_safe, :photos %></p>
            </div>

            <%= f.submit "Continuer", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/spots/_infowindow.html.erb
<div class="infomap text-center" style="width: 200px">
  <p><%= image_tag @my_spot.photos.first.picture.url(:thumb), width: '200' %><p>
  <p><%= @my_spot.title %></p>
</div>

app/views/spots/edit.html.erb
<div class="title-new text-center">
  <h2>Update your ad</h2>
  <p>Feel free to update your ad information or add photos</p>
</div>

<%= render 'form' %>

app/views/spots/index.html.erb
<div class="sidebar sidebar-padded">
  <!-- form to add specific filters and refresh this page -->
  <div class="row">
    <div class="col-xs-12">
      <%= form_tag(spots_path, method: 'get') do %>
        <div class="row">
          <div class="col-sm-7">
            <div class="form-group">
              <%= label_tag :price, "Max price:" %>
              <%= text_field_tag :price, nil, class: 'slider-price span2', data: { :"slider-id" => 'slider-price', :"slider-min" => @min_price, :"slider-max" => @max_price, :"slider-step" => 10, :"slider-value" => @max_price } %>
            </div>
            <div class="form-group">
              <%= label_tag :area, "Min area:" %>
              <%= text_field_tag :area, nil, class: 'slider-area span2', data: { :"slider-id" => 'slider-area', :"slider-min" => @min_area, :"slider-max" => @max_area, :"slider-step" => 5, :"slider-value" => @min_area, :"slider-selection" => "after"} %>
            </div>
            <div class="form-group">
              <%= label_tag :rating, "Min rating:" %>
              <%= text_field_tag :rating, nil, class: 'slider-rating span2', data: { :"slider-id" => 'slider-rating', :"slider-min" => 0, :"slider-max" => @max_rating, :"slider-step" => 1, :"slider-value" => 0, :"slider-selection" => "after" } %>
            </div>
            <div class="form-group form-inline">
              <!-- <%= label_tag :city, "City:" %> -->
              <%= hidden_field_tag :city, @params["city"], class: 'form-control' %>
            </div>
          </div>
          <div class="col-md-5">
            <div class="form-group">
              <%= label_tag :exceptional_view, "Exceptional view:" %>
              <%= check_box_tag :exceptional_view, checked: false, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= label_tag :modular_furniture, "Modular furniture:" %>
              <%= check_box_tag :modular_furniture, checked: false, class: 'form-control' %>
            </div>
          </div>
          <div class="text-center">
            <%= submit_tag "Find", class: 'btn btn-primary' %>
          </div>
        </div>

      <% end %>
    </div>
  </div>


  <!-- show all spots according to filters -->
  <div class="row">
    <div class="col-xs-12" style="padding-top: 30px;">
      <p><%= @spots_total_number %> results in <%= (@params["city"].nil? || @params["city"] == "") ? "the whole world" : @params["city"].capitalize %> :</p>
    </div>

    <% @spots_selected.each do |spot| %>
      <div class="col-md-6">
        <div class="card">
          <span class="card-bg" style="background-image: url(<%= image_path spot.photos.first.picture.url(:medium) %>)"></span>
          <span class="card-gradient"></span>
          <span class="card-rating">

            <%= ("<i class='fa fa-star' style='color: #469AE0;'></i>" * spot.rating).html_safe %><%= ("<i class='fa fa-star' style='color: white;'></i>" * (5 - spot.rating)).html_safe %>
          </span>
          <span class="card-price">
            <%= spot.price.to_i.to_s + ' €/day' %>
          </span>
          <%= link_to "", spot_path(spot),class: 'card-link' %>
        </div>
        <div class="card-detail">
          <div class="title"><%= spot.title %></div>
        </div>

      </div>
    <% end %>
    <div class="row"></div>
    <%= paginate @spots_selected %>
  </div>
</div>
<!-- block for map -->

<div id="map"></div>


<%= content_for(:after_js) do %>
  <!-- script for sliders -->
  <%= javascript_tag do %>
    var sliderPrice = $('.slider-price').slider();
    var sliderArea = $('.slider-area').slider();
    var sliderRating = $('.slider-rating').slider();
    <% if @params["price"].to_i > 0 %>
      var valuePrice = <%= @params["price"].to_i %>;
      sliderPrice.slider('setValue', valuePrice);
    <% end %>
    <% if @params["area"].to_i > 0 %>
      var valueArea = <%= @params["area"].to_i %>;
      sliderArea.slider('setValue', valueArea);
    <% end %>
    <% if @params["rating"].to_i > 0 %>
      var valueRating = <%= @params["rating"].to_i %>;
      sliderRating.slider('setValue', valueRating);
    <% end %>
  <% end %>
  <!-- script for map -->
  <%= javascript_tag do %>
    var myStyle = [{"featureType":"landscape.natural","elementType":"geometry.fill","stylers":[{"visibility":"on"},{"color":"#e0efef"}]},{"featureType":"poi","elementType":"geometry.fill","stylers":[{"visibility":"on"},{"hue":"#1900ff"},{"color":"#c0e8e8"}]},{"featureType":"road","elementType":"geometry","stylers":[{"lightness":100},{"visibility":"simplified"}]},{"featureType":"road","elementType":"labels","stylers":[{"visibility":"off"}]},{"featureType":"transit.line","elementType":"geometry","stylers":[{"visibility":"on"},{"lightness":700}]},{"featureType":"water","elementType":"all","stylers":[{"color":"#7dcdcd"}]}];

    $(document).on('ready', function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' }, provider: { styles: myStyle } }, function(){
        markers = handler.addMarkers(<%= raw @markers.to_json %>);
        console.log(markers);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });

      <!-- infowindow on mouseover -->
      google.maps.event.addListener(marker, 'mouseover', function() {
          infowindow.open(map, this);
      });

      // assuming you also want to hide the infowindow when user mouses-out
      google.maps.event.addListener(marker, 'mouseout', function() {
          infowindow.close();
      });
    });
  <% end %>
<% end %>

app/views/spots/new.html.erb
<div class="title-new text-center">
  <h2>Finalize your add</h2>
  <p>Spotit make you earn money renting your flat to photograph and video makers</p>
</div>


<%= render 'form' %>


<% content_for(:after_js) do %>
  <% javascript_tag do %>
    <!-- limit the number of pictures -->
    $(document).on('nested:fieldAdded', function(event){
      if ($('#pics .fields:visible').length > 2) {
      console.log('sup 2')
        $('#pics>p>a').hide();
      } else {
        $('#pics>p>a').show();
      }
    })
    $(document).on('nested:fieldRemoved', function(event){
      $('#pics>p>a').show();
    })

    $('#spot_address').keyup(function(){
      var address = $('#spot_address').val()
    })
    $('.new-spot').on('submit', function(){
      $('#spot_address').val() = address
    })

  <% end %>
<% end %>

app/views/spots/show.html.erb
<div class="banner">
  <span class="banner-bg" style="background-image: url(<%= image_path @spot.photos.first.picture.url(:large) %>); backgroun-position: center center;"></span>
  <span class="banner-gradient"></span>
  <a href=<%= image_path @spot.photos.first.picture.url(:large) %> class='banner-link' data-lightbox="roadtrip"></a>

  <% @spot.photos.each do |photo| %>
    <% if photo.id != @spot.photos.first.id && photo.picture_file_name %>
      <a href=<%= image_path photo.picture.url(:large) %> data-lightbox="roadtrip"></a>
    <% end %>
  <% end %>

</div>

<div class="container">
  <div class="row">
    <div class="col-sm-6 col-md-offset-1">

      <div class="row">
        <div class="col-sm-2 col-xs-hidden">
          <%= image_tag @owner.imageUrl, height: '70', class: 'img-circle', style: 'margin-top: 22px' %>
        </div>
        <div class="col-sm-10">
          <!-- displaying the title -->
          <h2><%= @spot.title %></h2>

          <!-- displaying the address -->
          <address style="margin-bottom: 10px;">
            <%= @spot.address %>
          </address>
          <p><%= ("<i class='fa fa-star' style='color: #FFCE54;'></i>" * @spot.rating).html_safe %><%= ("<i class='fa fa-star' style='color: #eee;'></i>" * (5 - @spot.rating)).html_safe %></p>
        </div>
      </div>

      <!-- displaying all the features of the spot -->
      <div class="row text-center icons-row">
        <div class="col-xs-6 col-sm-3 col-md-2">
          <%= image_tag "style.png", height: '40' %>
          <p><%= @spot.style %></p>
        </div>
        <div class="col-xs-6 col-sm-3 col-md-2">
          <%= image_tag "squaremeter.png", height: '40' %>
          <p><%= @spot.area %> m2</p>
        </div>
        <div class="col-xs-6 col-sm-3 col-md-2">
          <%= image_tag "exposition.png", height: '40' %>
          <p><%= @spot.exposition %></p>
        </div>
        <div class="col-xs-6 col-sm-3 col-md-2">
          <%= image_tag "furniture.png", height: '40' %>
          <p><%= @spot.modular_furniture ? "modular" : "not modular" %></p>
        </div>
        <% if @spot.exceptional_view %>
          <div class="col-xs-6 col-sm-3 col-md-2">
            <%= image_tag "view.png", height: '40' %>
            <p> "view" </p>
          </div>
        <% end %>
      </div>

      <!-- displaying the description -->
      <div class="row" style="text-align: justify;">
        <h3>Know more about this place</h3>
        <p><%= @spot.description %></p>
      </div>

      <!-- commentaires -->
      <div class="row">
        <h3>All reviews</h3>
        <% if @spot.spot_reviews.blank? %>
          <p>No reviews yet.</p>
        <% end %>
        <% @spot.spot_reviews.each do |spot_review| %>
          <div class="col-xs-12">
            <div class="review">
              <%= image_tag spot_review.user.imageUrl, height: '50', class: 'img-circle', style: '' %>
              <%= ("<i class='fa fa-star' style='color: #FFCE54;'></i>" * spot_review.rating).html_safe %><%= ("<i class='fa fa-star' style='color: #eee;'></i>" * (5 - spot_review.rating)).html_safe %> - <%= spot_review.created_at.strftime('%m/%d/%y') %>
              <p style='margin-left: 50px;'><%= spot_review.comment %></p>
            </div>
          </div>
        <% end %>

        <!-- Add a review -->
        <% if user_signed_in? %>
          <% if current_user.booked_spot?(@spot) && !current_user.reviewed(@spot) %>
            <div class="col-xs-12">
              <button class="btn btn-primary" id="add-booking">Add a review</button>
              <div>
                <%= render 'spot_reviews/new' %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>



    <!-- displaying the "ask for bookings - it does not create a booking yet but redirect to the New booking with the good params" -->
    <div class="col-sm-4">
      <div class="background-grey card-big">
        <div class="row text-center">
          <div class="price-content">
            <%= form_tag( new_spot_booking_path(@spot), method: 'get') do %>
              <div class="form-group form-inline">
                <p><%= label_tag :start_time, "Start time" %></p>
                <%= text_field_tag :start_time, Time.now.strftime("%m/%d/%Y"), type: "text", class: 'form-control datepicker' %>
              </div>
              <div class="form-group form-inline">
                <p><%= label_tag :end_time, "End time" %><p>
                <%= text_field_tag :end_time, Time.now.strftime("%m/%d/%Y"), type: "text", class: 'form-control datepicker' %>
              </div>
              <div class="form-group form-inline">
                <%= hidden_field_tag :total_price, @spot.price.to_i, class: 'form-control' %>
              </div>
              <div class="price-bordered text-center">
                <p id="tt_days">1 day<p>
                <h3 id="tt_price"><%= @spot.price.to_i %> €</h3>
              </div>
              <div class="text-center">
                <%= submit_tag "Book", class: 'btn btn-primary' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="row text-center">
        <div class="card-map">
        <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=15&size=300x300&sensor=false&maptype=roadmap&markers=color:blue|#{@spot.address}" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row padded"></div>
</div>


<!-- displaying the javascript -->
<% content_for(:after_js) do %>
<!-- compulsory to use datepicker -->
  <script type="text/javascript">
    $(document).ready(function(){
      $('.datepicker').datepicker({
        startDate: 'd'
      });
      $('.datepicker').on('changeDate', function(ev){
          $(this).datepicker('hide');
      });
    });
  </script>
<% end %>
<!-- used to set the price automatically -->
<% content_for(:after_js) do %>
  <% javascript_tag do %>

    $('.form-group').on('change', function() {

   <!--  getting all the variables from the form -->
      var start_date = new Date( $('#start_time').val());
      var end_date = new Date($('#end_time').val());
      var laps = (end_date - start_date) / (1000 * 60 * 60 * 24) + 1

  <!--  calculating the total price for the booking-->
      var total_price = Math.round(
        <%= @spot.price %> * laps) ;

  <!--  Setting the total price for the booking-->
      $("#total_price").val(total_price);

  <!--  Displaying to the view the total price for the booking-->
      $("#tt_price").text(total_price + ' €');
      if (laps > 1) {
        $("#tt_days").text(laps + ' days');
      } else {
        $("#tt_days").text('1 day');
      }

    })
  <% end %>
<% end %>