config/routes.rb
Rails.application.routes.draw do
devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  get 'add' => 'pages#add'

  resources :users

  resources :spots, only: [:index, :show, :new, :create, :edit, :update] do
    # resources :doses, only: [:new, :create] // pour faire plaisir au rake
    resources :bookings, only: [:index,:new, :create, :show, :edit, :update]
    resources :spot_reviews, only: [:index, :new, :create, :edit, :update, :destroy]

  end
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  alias_attribute :user, :renter
  belongs_to :spot
  belongs_to :user


  def owner
    spot.user
  end

  validates :total_price, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true

  private


end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_spot, only: [:new, :create,:show, :edit, :update]
  before_action :set_booking, only: [:show, :edit, :update, :delete]
  before_action :set_params, only: [:index, :new]
  before_filter :store_location
  before_action :authenticate_user!



  def show

  end

  def new
    @booking = Booking.new()
  end

  def create

    @params = booking_params
    @booking = Booking.new(booking_params)
    @booking.spot = @spot
    # @booking.total_price = @spot.price *(@booking.start_time-@booking.end_time)
    if @booking.save
      BookingMailer.booking_confirmation(@spot,@booking).deliver_now
      redirect_to user_path(current_user)
    else
      render :new
    end
  end


  def edit
  end

  def update
    @booking.update(params[:id])
  end

  def delete
    @booking.delete
  end

  private
  def set_spot
    id = params[:spot_id]
    @spot = Spot.find(id)
  end

  def set_params
    @params = params
  end
  def set_booking
    id = params[:id]
    @booking = @spot.booking.find(id)
  end

  def booking_params
    params.require(:booking).permit(:start_time, :end_time, :spot_id, :user_id, :total_price)
  end

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/edit.html.erb
      <%= simple_form_for([ @spot, @booking ]) do |f| %>
        <%= f.input :start_time %>
        <%= f.input :end_time %>
        <%= f.input :total_price %>
        <%= f.submit %>
      <% end %>

app/views/bookings/new.html.erb
<div class="title-new text-center">
  <h2>Final step to book this great place</h2>
  <p>Please confirm your booking</p>
</div>

<div class="background-grey">
  <div class="container">
    <div class="row">
      <div class="title-new text-center">
        <h2> <%= @spot.title %></h2>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <div class="margin-form">
          <div class="price-bordered text-center">
            <p id="tt_days">1 day<p>
            <h3 id="tt_price"><%= @spot.price.to_i %> €</h3>
          </div>
          <p class="card-margin  "> The dates you have chosen: </p>
          <%= simple_form_for([ @spot, @booking ]) do |f| %>
            <%= f.input :start_time, as: :string, input_html: {class: "datepicker", value: @params["start_time"]}%>
            <%= f.input :end_time, as: :string, input_html: {class: "datepicker", value: @params["end_time"] } %>
            <%= f.hidden_field :total_price, value: @params["total_price"] %>
             <%= f.hidden_field :spot_id, value: @spot.id %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <div data-toggle="modal" data-target="#myModal">
            <%= f.submit "Confirm your booking", class: "btn btn-primary"%>
            </div>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>

<script type="text/javascript">
  $(document).ready(function(){
  $('.datepicker').datepicker({
        startDate: 'd'
    });
  $('.datepicker').on('changeDate', function(ev){
      $(this).datepicker('hide');
  });
  });
</script>
<% end %>


<% content_for(:after_js) do %>
  <% javascript_tag do %>

    $('.simple_form').on('change', function() {

   <!--  getting all the variables from the form -->
      var start_date = new Date( $('#booking_start_time').val());
      var end_date = new Date($('#booking_end_time').val());
      var laps = (end_date - start_date) / (1000 * 60 * 60 * 24) + 1

  <!--  calculating the total price for the booking-->
      var total_price = Math.round(
        <%= @spot.price %> * laps) ;

  <!--  Setting the total price for the booking-->
      $("#total_price").val(booking_total_price);
      $("#tt_price").val('Total price : ' + total_price + ' €');

      $("#tt_price").text(total_price + ' €');
      if (laps > 1) {
        $("#tt_days").text(laps + ' days');
      } else {
        $("#tt_days").text('1 day');
      }
    })
  <% end %>
<% end %>


<!-- Modal -->
<div class="modal" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h2 class="modal-title" id="myModalLabel">Thank you</h2>
      </div>
      <div class="modal-body">
        Thank you very much, your booking has been taken into account. The spot owner will get back to you soon.
      </div>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container">
 <div class="row">
    <div class="col-xs-12">
      <h3>Your Booking has been succesfully transmitted, you will receive a confirmation email </h3>
    </div>
    <div class="col-xs-12">
      <p style="height:100px" class="text-center"><%= image_tag "yes.png" %> </p>
    </div>
    <div class="col-xs-12">
      <button class="btn btn-default"><%= link_to "go back to the Spot Description", spot_path(@spot) %></button>
      <button class="btn btn-default"><%= link_to "go back to the Spots lists", spots_path %></button>
    </div>
  </div>
</div>