config/routes.rb
Rails.application.routes.draw do
devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  get 'add' => 'pages#add'

  resources :users

  resources :spots, only: [:index, :show, :new, :create, :edit, :update] do
    # resources :doses, only: [:new, :create] // pour faire plaisir au rake
    resources :bookings, only: [:index,:new, :create, :show, :edit, :update]
    resources :spot_reviews, only: [:index, :new, :create, :edit, :update, :destroy]

  end
end

app/views/pages/add.html.erb
<div class="title-new text-center">
  <h2>Publish your add</h2>
  <p>Spotit make you earn money renting your flat to photograph and video makers</p>
</div>

<div class="background-grey">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-md-5 col-md-offset-1">
        <div class="margin-form">
          <%= form_tag(new_spot_path, method: 'get') do %>
            <div class="form-group form-inline">
              <p><%= label_tag :city, "City:" %></p>
              <%= text_field_tag :city, nil, placeholder: "ex: Paris, Lyon...", class: 'form-control' %>
            </div>
            <div class="form-group form-inline">
              <p><%= label_tag :area, "Area:" %><p>
              <%= text_field_tag :area, nil, placeholder: "(in sqm)", class: 'form-control' %>
            </div>
            <div class="text-right">
              <%= submit_tag "Continue", class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="col-sm-6 col-md-5 hidden-xs">
        <div class="box">
          <div class="row flex">
            <div class="col-md-6 text-center">
              <p>See the money you can make by renting your place to shooting profesionals:</p>
            </div>
            <div class="col-md-1">
              <i class="fa fa-arrow-right"></i>
            </div>
            <div class="col-md-5 text-center">
              <h1 id="estimated_earning">0€</h1>
            <img src="https://a2.muscache.com/airbnb/static/landing_pages/mentorship/earn-money-f250d63dd518732d366297a3183a4b4d.png">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<% content_for(:after_js) do %>
  <% javascript_tag do %>
    <!-- update price on key press  -->
    $('#area').on('keyup', function() {
      var area = $(this).val();
      var total_price = area * 4;
      $("#estimated_earning").text(total_price + ' €');
    })
    <!-- update price on click -->
    $('#area').on('click', function() {
      var area = $(this).val();
      var total_price = area * 4;
      $("#estimated_earning").text(total_price + ' €');
    })
  <% end %>
<% end %>

app/views/pages/home.html.erb
<% content_for :nav, render('shared/navbar_home') %>


<div class="background">
  <div class="bg-gradient flex">
    <div class="form-group">
      <%= form_tag('/spots', method: 'get', :class => "form-inline") do %>
         <div class="title-home"><span class="box-home"><%= select_tag :city, options_for_select(%w( PARIS LYON BORDEAUX )) %></span><span class="glyphicon glyphicon-chevron-down" aria-hidden="true" style="font-size: 35px;"></span> EST VOTRE STUDIO</div>
         <span id="hiddenDiv" class="title-home" style="visibility:hidden; line-height:0;"></span>
         <div class="text-center">
          <%= submit_tag "Find your perfect place", class: 'btn btn-primary btn-home' %></div>
      <% end %>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>
  <% javascript_tag do %>
    <!-- JS to make the chevron open the select -->
    $('.glyphicon').click(function() {
        open($('#city'));
    });

    function open(elem) {
      if (document.createEvent) {
        var e = document.createEvent("MouseEvents");
        e.initMouseEvent("mousedown", true, true, window, 0, 0, 0, 0, 0, false, false, false, false, 0, null);
        elem[0].dispatchEvent(e);
      } else if (element.fireEvent) {
        elem[0].fireEvent("onmousedown");
      }
    }

    <!-- JS to adapt select size to content to center the div-->
    <!-- at the beginning -->
    $('#hiddenDiv').html( $('#city').val() );
    $('#city').width( $('#hiddenDiv').width() );

    <!-- and on change -->
    $('#city').change( function() {
      $('#hiddenDiv').html( $('#city').val() );
      $('#city').width( $('#hiddenDiv').width() );
    });
  <% end %>
<% end %>